### ISSUE TITLE
an issue with PHP 8.x and this plugin

### ISSUE THREAD

**Issue by MattWeatherford** [dwc/wordpress-plugin-http-authentication#1]
Having a problem getting this plugin's settings screen to show up in Wordpress 

I I try to manually go to:  https://mywpsitedns/wp-admin/options-general.php?page=http-authentication%2Fhttp-authentication.php 
but I get the error:

"Sorry, you are not allowed to access this page."

When I mouse over "settings" on the left side of the wp-admin area, I dont see the "HTTP Auth" settings there.  I do see it on another site though that I have.

It turns out that if I downgrade my ubuntu 22.04 distro's PHP to 7.4 then it works again.

There seems to be an issue with PHP 8.x and this plugin.

**Comment by mvl22** [comment]
The problem is that the two .php classes use old-style constructors, which PHP8 does not support. As such, the vast bulk of the code simply isn't being run at all.

If you change them to use `__construct`, as per the pull request above, that will work perfectly.

I hope this can be accepted and then pushed as a new 4.6 release, for this useful little plugin.

**Comment by dwc** [comment]
Thanks, @mvl22! Version 4.6 is now in the plugin directory:

https://wordpress.org/plugins/http-authentication/
